version: '3.3'

services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    expose:
      - 80
    ports:
      - 80:8000
    volumes:
      - .:/renatcoach
    command: python manage.py runserver 0.0.0.0:8000


volumes:
  postgres_data: