# Generated by Django 2.2.9 on 2020-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Анонимный пользователь', max_length=1024)),
                ('phone', models.CharField(blank=True, default='88008880088', max_length=1024)),
                ('tariff', models.IntegerField(blank=True, default=-1)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mail',
                'verbose_name_plural': 'mails',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, default='Новый тариф', max_length=1024)),
                ('short', models.CharField(blank=True, default='Тариф', max_length=1024)),
                ('warning_message', models.CharField(blank=True, max_length=1024, null=True)),
                ('warning_color', models.CharField(blank=True, default='#1771F1', max_length=1024)),
                ('price_value', models.IntegerField(blank=True, default=0, null=True)),
                ('price_label', models.CharField(blank=True, default='<span>0</span> рублей', max_length=1024)),
                ('image', models.CharField(blank=True, max_length=1024, null=True)),
                ('button_name', models.CharField(blank=True, default='Договориться', max_length=1024)),
                ('url', models.CharField(blank=True, default='#mail', max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mail',
                'verbose_name_plural': 'mails',
                'ordering': ['number'],
            },
        ),
    ]
