# Generated by Django 2.2.9 on 2020-05-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['number'], 'verbose_name': 'tariff', 'verbose_name_plural': 'tariffs'},
        ),
    ]
